/// <reference types="expo/types" />

// This reference also lives in `expo-env.d.ts`, but that file is generated by the
// Expo CLI and is gitignored — so on a fresh clone `tsc --noEmit` would fail on the
// `import '../global.css'` in `app/_layout.tsx` before anyone had run `expo start`.
// Declaring it here keeps the typecheck gate self-sufficient.
